// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from "vue";
import { CesiumWidget, Terrain } from "@cesium/engine";
import { CESIUM_VERSION } from "virtual:cesium/version";

const container = ref<HTMLDivElement>();
let widget: CesiumWidget;

onMounted(() => {
  console.log(CESIUM_VERSION);
  widget = new CesiumWidget(container.value!, {
    terrain: Terrain.fromWorldTerrain(),
  });
});

onBeforeUnmount(() => {
  widget?.destroy();
});
</script>

<template>
  <div ref="container" style="width: 100%; height: 100%" />
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { CesiumWidget, Terrain } from "@cesium/engine";
  import { CESIUM_VERSION } from "virtual:cesium/version";

  let container: HTMLDivElement;

  onMount(() => {
    console.log(CESIUM_VERSION);
    const widget = new CesiumWidget(container, {
      terrain: Terrain.fromWorldTerrain(),
    });
    return () => widget.destroy();
  });
</script>

<div bind:this={container} style="width: 100%; height: 100%" />
